#!/usr/bin/env bash
# python -m torch.distributed.launch --nproc_per_node 8 run_speech_recognition_seq2seq.py \
CUDA_VISIBLE_DEVICES="0" python run_speech_recognition_seq2seq.py \
	--dataset_name="facebook/voxpopuli" \
	--model_name_or_path="./seq2seq_wav2vec2_bart-base_scratch" \
	--dataset_config_name="en" \
	--train_split_name="train" \
	--eval_split_name="validation" \
	--output_dir="./seq2seq_wav2vec2_bart-base_scratch/training_voxpopuli" \
	--preprocessing_num_workers="1" \
	--dataloader_num_workers="8" \
	--dataloader_prefetch_factor="2" \
	--length_column_name="input_length" \
	--overwrite_output_dir \
	--num_train_epochs="35" \
	--per_device_train_batch_size="96" \
	--per_device_eval_batch_size="96" \
	--gradient_accumulation_steps="1" \
	--learning_rate="5e-5" \
	--lr_scheduler_type="cosine_with_min_lr" \
	--lr_scheduler_kwargs="{\"min_lr\": 1e-6}" \
	--warmup_steps="2000" \
	--eval_strategy="steps" \
	--text_column_name="normalized_text" \
	--save_strategy="no" \
	--eval_steps="1000" \
	--logging_steps="10" \
	--save_total_limit="1" \
	--bf16 \
    --task="transcribe" \
	--predict_with_generate \
	--do_train --do_eval \
	--do_lower_case \
    --trust_remote_code \
    --report_to="wandb" \
	--sclite_path="/storage/brno2/home/xhorni20/dp_mit/SCTK/bin/sclite" \
	--wandb_project="seq2seq_encoder-decoder_scratch" \
	--cache_dir="$SCRATCHDIR/preprocessed_dataset_voxpopuli" \
